### ISSUE TITLE
dedicated integration test for quickgen + spectro pipeline

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#167]
Context: quickgen uses specsim to simulate the full spectro pipeline output at multiple levels: fiberflats, uncalibrated extracted spectra, sky model, stdstar models, flux calibration vectors, fully calibrated spectra.  In principle the full pipeline should be able to pick up at any of these intermediate stages and continue running as if they had been generated by the full pipeline instead of quickgen.

quickgen has unit tests but we've occasionally had problems with it outputting files that can't be used as input to the next pipeline step.  e.g. the last case was when the pipeline started requiring the the fibermap be included in the frame files, but we forgot to add that to quickgen too (that has been fixed).

In anticipation of using quickgen more and more, please write a dedicated quickgen integration test to make sure that its outputs still work as pipeline inputs.  e.g. something like:

* Use newexp-desi to generate a simspec file with ~25 spectra
* Run quickgen on those to generate frame, fiberflat, sky, stdstars, calib, and cframe files
* Run the desispec pipeline steps to confirm that they work with the quickgen files as inputs, e.g.
  * desi_compute_fiberflat (frame -> fiberflat)
  * desi_compute_sky (frame & fiberflat -> sky)
  * desi_fit_stdstars (frame & fiberflat & sky -> stdstars)
  * desi_compute_fluxcalibration (frame & fiberflat & sky & stdstars -> fluxcalib)
  * desi_process_exposure (everything -> cframe)
  * desi_make_bricks (cframe -> bricks)

This would probably take long enough that we wouldn't run it as part of the unit tests but we'd run it as a separate test similar to (but separate from) py/desispec/test/integration_test.py for pixsim+spectro pipeline.

**Comment by rstaten** [comment]
@sbailey I have written this integration test and I will push it to a branch soon. The only issue that arrises when sending quickgen output through the full pipeline is due to astype with respect to the output wavelength array in the quickgen calib file. I can add .astype('f4') to line 91 in desispec.io.fluxcalibration to fix this, but if I do not then I get an error when running desi_process_exposure.

Also, I do not include the first step that you mention (frame -> fiberflat) because quickgen only outputs fiberflat files for a flat exposure and skips the process of outputting frame files. If this needs to be tested as well, then I can update quickgen to allow for frame files as output for flat exposures.

**Comment by rstaten** [comment]
@sbailey I have written this integration test and I will push it to a branch soon. The only issue that arises when sending quickgen output through the full pipeline is due to astype with respect to the output wavelength array in the quickgen calib file. I can add .astype('f4') to line 91 in desispec.io.fluxcalibration to fix this, but if I do not then I get an error when running desi_process_exposure.

Also, I do not include the first step that you mention (frame -> fiberflat) because quickgen only outputs fiberflat files for a flat exposure and skips the process of outputting frame files. If this needs to be tested as well, then I can update quickgen to allow for frame files as output for flat exposures.

**Comment by sbailey** [comment]
Fixed by #179; closing
