### ISSUE TITLE
write some code to deal with the DB white dwarf models

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#200]
The white dwarf models now include both DB and DA white dwarfs (as indicated by the ```WDTYPE``` tag in the metadata table).  Need to write some code to generate the requested white dwarf type.  See also https://github.com/desihub/desisim-testdata/pull/6.

**Comment by sbailey** [comment]
For consideration: the redshift fitting outputs include a "SUBTYPE" column.  Its exact usage remains to be defined, but it is a placeholder for things like stellar classifications wanting to record a subtype while QSO classifications might want to record a subtype from a different set of options.

Should/could template metadata do the same? — a catch-all SUBTYPE column whose options depend upon what type of template it is, rather than carrying a WDTYPE column that is meaningful for only a small fraction of the overall targets.

**Comment by moustakas** [comment]
Implementing this would require a somewhat annoying regeneration of the metadata tables (at least for white dwarfs and stars).  Could we just do this on-the-fly as needed when the template-generating code gets called, e.g., in ```newexp-desi```?  We do something like this (i.e., picking and choosing what we want from the template metadata tables and renaming some columns) anyway...

**Comment by moustakas** [comment]
Addressed in #213.
