### ISSUE TITLE
Create function to build spectra from targets+truth information

### ISSUE THREAD

**Issue by forero** [desihub/desisim#203]
The function should be something like this (suggested by @sbailey )
```python
def get_target_spectra(targets, truth, wave=None):
    '''
    Returns true flux, wavelengths, and template metadata for input targets
    
    Args:
        targets: rows of target selection table
        truth: row-matched truth information corresponding to targets
    
    Optional:
        wave: wavelength array to sample the output templates
    
    Returns (flux,wave,meta) analogous to desisim.templates.XYZ.make_templates()
        flux: 2D[ntarget, nwave] array of flux [erg/s/cm2/Angstrom]
        wave: 1D[nwave] array of sampled wavelengths [Angstroms]
        meta: metadata table for these targets

    Note:
        targets and truth come from input mocks via
        desitarget.build.select_mock_targets().
    
    TODO:
        Document exactly which columns of `targets` and `truth` are needed.
    '''
```

**Comment by forero** [comment]
To generate Lya spectra we would also need the information linking back to the mock files (the forest is stored there). A new column that could be added to `truth` should be `MAG_G`, as it is needed to complete the full spectrum using `desisim.templates.QSO`.

**Comment by forero** [comment]
`ZMETAL`,   `AGE`,     `TEFF`,    `LOGG`    and `FEH` are other columns that could be added to `truth` and facilitate the creation of `MWS` spectra.

**Comment by moustakas** [comment]
The ```truth``` catalog also needs to have the apparent magnitude of each source, ```MAG``` which is used to normalize the spectra.  Unfortunately ```desisim.templates``` also needs to know the normalizing filter name, which would be annoying to have as a separate column (since our mocks rely on at most 2-3 different filters).

One possibility would be to use different suffixes on ```MAG```, for example, ```MAG_R``` would map to ```normfilter = decam2014-r```, ```MAG_R_SDSS``` would map to ```normfilter = sdss2010-r```, and so forth.  But then we end up with a bunch of empty values for many sources, which is even more wasteful.

**Comment by moustakas** [comment]
I think this issue has been closed / superseded by developments in `desitarget.`
