### ISSUE TITLE
speeding up desisim.lya_spectra

### ISSUE THREAD

**Issue by forero** [desihub/desisim#207]
Running [`desisim.lya_spectra`](https://github.com/desihub/desisim/blob/master/py/desisim/lya_spectra.py) to generate LyaQSO spectra takes on average ~2 seconds per spectrum (~1 month for the whole set of objects in the mocks!) on a login node.  Most of the time is spent in [`qso.make_templates`](https://github.com/desihub/desisim/blob/master/py/desisim/templates.py#L1601). What would be the best strategy to speed it up?

**Comment by sbailey** [comment]
Was this timing test done for a single spectrum, or requesting N>>1 and dividing the time by N?

If we can't speed up the individual operations, parallelizing over bricks (or even within bricks and recombining) would be a brute force option for shortening the walltime.

**Comment by moustakas** [comment]
Echoing @sbailey's question, ```qso.make_templates``` is vectorized and should be able to generate thousands of spectra relatively quickly (although I haven't formally timed the code). So can you provide a few more details about how you tested this?

**Comment by forero** [comment]
I tested the code generating 1000 spectra at a time, running from ipython in a login node at NERSC, using %timeit. The 2sec/spectra come from getting the best timing and dividing by N=1000.

**Comment by forero** [comment]
any hints on how to speed up the code @sbailey @moustakas ?

**Comment by moustakas** [comment]
I'm sorry I have not had time to look into this.  The core algorithm was written by @profxj but then I modified it to accept input redshift and magnitude arrays.  Could you profile the code to see where specifically in ```qso.make_templates``` it's spending most of its time?

**Comment by forero** [comment]
@moustakas @sbailey cProfile says that 70% of the time is spent here https://github.com/desihub/desisim/blob/master/py/desisim/qso_template/desi_qso_templ.py#L348 doing cosmology calculations. I will explore some solutions tomorrow.

**Comment by sbailey** [comment]
Adding a @profxj mention as the original author of the code that uses that.

We could make an approximate lookback_distance vs. z spline or polynomial and replace all these calculations with a much faster evaluation of those.

**Comment by profxj** [comment]
I've taken a look at this and have some thoughts.

Let me start from the code I wrote: desi_qso_templates()
  This module was written to generate N_perz mock spectra per redshift interval with the default
zmnx=(0.4, 4) and stepsize z_wind=0.2.  Someone (probably me) has modified it so that
it may create a spectra at any input redshift (or redshifts).

The QSO() class which I presume @moustakas wrote is calling desi_qso_templates()
one redshift at a time for a total of nmodel calls.  It requests 50 spectra per call (this
is padded by a factor of 20 in desi_qso_templates but I suspect the number generated
is close to 50 and not 1000) and saves one if it passes the color cuts.

I think we can reduce the time in the cosmo calculations by moving 
lines 347-349 in desi_qso_templates up near line 300 or even out of the loop over z0
altogether (zrand would need to move too).

I might also suggest, however, that desisim.templates.QSO() be modified to call desi_qso_templates()
only once.   I don't think there will be a memory issue and the book-keeping would be similar.
This would avoid generating the astropy.cosmology object over and again (alternatively, generate
it in QSO() and pass it in) and all the I/O of reading the PCA files.

**Comment by moustakas** [comment]
Thanks, @profxj.  I hacked your code to work with an input redshift/magnitude vector and didn't think about overhead or speed.  @forero can you implement the proposed changes?

**Comment by forero** [comment]
@moustakas sure, I can implement the changes.

**Comment by moustakas** [comment]
Closed in #210
