### ISSUE TITLE
problem using desisim/master module from an edison interactive node

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#216]
Could this be one of those intermittent NERSC errors?  Can anyone else reproduce this?  I get the following crash below (and wasn't previously) when loading the master branch of desisim.  Oddly, this doesn't happen on the login node, only when requesting an interactive node (on edison).

```
ioannis@edison02:~% salloc -N 1 -p debug -L SCRATCH,project
[snip]
ioannis@nid00294:~% source /project/projectdirs/desi/software/desi_environment.sh
ioannis@nid00294:~% module swap desisim/master
ioannis@nid00294:~% python -c 'from desisim.qso_template import desi_qso_templ as dqt'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 766, in get_code
  File "<frozen importlib._bootstrap_external>", line 819, in get_data
OSError: [Errno 5] Input/output error
```

**Comment by moustakas** [comment]
But if I git-clone and checkout my own master branch this doesn't happen.

**Comment by sbailey** [comment]
This is reproducible and appears to be a problem reading some files on /global/common from compute nodes.  I'll submit a ticket with NERSC and report back here when it is fixed.
```
<edison ~> ls -l /global/common/edison/contrib/desi/code/desisim/master/py/desisim/qso_template/__init__.py 
-rw-r----- 1 desi desi 0 Feb  2 16:17 /global/common/edison/contrib/desi/code/desisim/master/py/desisim/qso_template/__init__.py
<edison ~> cat /global/common/edison/contrib/desi/code/desisim/master/py/desisim/qso_template/__init__.py 
cat: /global/common/edison/contrib/desi/code/desisim/master/py/desisim/qso_template/__init__.py: Input/output error
```
I can cat the (0 sized) file from edison05 but not from a compute node nid00292

**Comment by sbailey** [comment]
From NERSC:
> This problem will persist until Edison undergoes the OS upgrade. The only solution is to make the file non-zero sized by adding an empty line (like "#") into /global/common/edison/contrib/desi/code/desisim/master/py/desisim/qso_template/__init__.py. It's a weird bug in DVS that is apparently fixed in the upgrade because we no longer see it on Cori.
> 
> Edison will be upgraded to a new OS, however, the exact date is still TBA. Hope the workaround works for you.

We apparently didn't encounter this before since our installed tags pre-compile the python into `__pycache__` directories and thus the code doesn't need to touch `__init__.py` itself.  The problem only occurs when running from raw uninstalled master copies on that particular filesystem from the compute nodes.  This is a bug in the OS/filesystem, but we can work around it with either

1. `python -m compileall -f <directory>` after each daily `git pull` update
2. actually `python setup.py install` the master copies after the `git pull`

I've patched up the existing master checkouts and will update my newly-revived-daily-update scripts to keep this up-to-date.  Reopen the ticket if you still have problems.
