### ISSUE TITLE
fix desisim API documentation

### ISSUE THREAD

**Issue by andreufont** [desihub/desisim#222]
I would like to get started with desisim, but I couldn't find documentation. If I go to 
http://desisim.readthedocs.io/en/latest/api.html
I get a bunch of error messages. Is it only me, or is the API documentation broken?

**Comment by weaverba137** [comment]
It is not only you.  The API documentation has not been well maintained, and there is no excuse for that.  The latest Travis build includes the warning messages: https://travis-ci.org/desihub/desisim/jobs/213548643.

**Comment by weaverba137** [comment]
Two updates:

1. Incorrect dependencies are being fed to readthedocs.  When the documentation is built *on the master branch* in an environment that has all the correct dependencies, no problems are reported.
2. The Travis build referenced is the test merge of PR #220.  So the documentation in that branch needs to be fixed.

**Comment by weaverba137** [comment]
Sorry, I was wrong about item 1 above.  The current master branch does have serious problems as well.

**Comment by weaverba137** [comment]
I am putting my money where my mouth is and working on some of these fixes.

**Comment by sbailey** [comment]
These problems arise because Travis claims the docs built successfully when in fact they have so many build warnings that they are uselessly bad.  If Travis gives it a "build passing", we shouldn't have to go read the Travis logs to see if that is really true.  What needs to happen to make doc "build passing" really mean that?

The current state of http://desisim.readthedocs.io/en/latest/api.html is deeply broken (but hopefully easily fixed) due to missing dependencies during the build.  A more common case for us is people writing docstrings that are perfectly readable by a human but not legal RST and thus break Sphinx.  If we can't get Travis to catch that latter case, could we add a unit test that would build the docs and fail if there are any syntax errors?

**Comment by weaverba137** [comment]
I addressed this in desihub/desispec#309.  To summarize: if we were using the astropy affiliated-package infrastructure, this would already be done for us.

What astropy does is *wrap* the documentation build in a script that captures its output, and then scans the output for warnings.

Unfortunately, this does not necessarily catch the case where Travis has some or all build dependencies installed, but readthedocs does not.

For now the best defense is to build the documents on one's own system and catch errors before they get checked in.

I would like to see more automation here, but I fear that other items have higher priority.
