### ISSUE TITLE
Use exposures.fits file as input observation list

### ISSUE THREAD

**Issue by weaverba137** [desihub/desisim#273]
`wrap-newexp` needs to be set up to read an exposures.fits file produced by `desisurvey.progress.Progress.get_exposures()`.  This input is specifically designed to make certain standardization steps unnecessary.

This issue will track some specific remaining questions prior to creating a PR:

1. If we write out the exposures list, after flats and darks are added, what do we call the file?  exposures.fits, but in a different directory?
2. When writing out the exposures list, the 'PROGRAM' for flats and darks is 'FLAT' and 'DARK', correct?
3. Did we already have specific dummy values in mind (for darks and flats) for things like 'MOONSEP', or would any arbitrary (but obviously dummy) value work?

**Comment by weaverba137** [comment]
Hmmm, 'FLAT' and 'DARK' would be the exposure 'FLAVOR', not 'PROGRAM', correct?  'FLAVOR' would actually be a new column that somehow hasn't been in the data model (for these files) or database schema before, as far as I can tell.

Flavor *does* appear in the raw data metadata database.

**Comment by weaverba137** [comment]
Sorry, I get 'ARC' confused with 'DARK'.  Wherever 'DARK' appears above, I mean 'ARC'.

**Comment by weaverba137** [comment]
Which suggests another question:  will there be "zero" exposures (shutter closed, exposure time = 0)?

**Comment by weaverba137** [comment]
In principle it would not be hard to simulate realistic values for the 'MJD' and 'EXPTIME' columns for the flats and arcs, rather than just put in, 0.0, for example.

**Comment by sbailey** [comment]
Proposing some specifics with the main goal of getting an `exposure.fits` file written to disk that includes arc/flat exposures and EXPIDs, while not requiring rerunning the full survey simulations if we want to change the number of arcs/flat/zero/darks per night:

Update `desisurvey.progress.Progress.get_exposures()` to include a FLAVOR column, with default values of "science" since that is the only flavor of exposure that desisurvey currently tracks.

New function `surveysim.add_calib` (or similar) that implements the logic currently in `desisim/bin/wrap-newexp` to add arcs/flats and assign exposure IDs:
```python
def add_calib(exposures, arcs_per_night=3, flats_per_night=3):
    '''
    Adds arc and flat exposures and assigns exposure IDs
    
    Args:
        exposures: table of exposures, e.g. from
            desisurvey.progress.Progress.get_exposures()

    Options:
        arcs_per_night: number of arc exposures to add per night
        flats_per_night: number of flat exposures to add per night
    
    Returns:
        new exposures table with an added/replaced EXPID column and additional
            rows for arc and flat exposures.
    '''
```
That's the minimum we need for now, but it could also be expanded for "zero" and "dark" exposures per night too.

New script `surveysim_add_calib` (or similar) that would
1. load `$DESISURVEY_OUTPUT/progress.fits` (with an option to override that path)
2. convert that to an exposures table using `desisurvey.progress.Progress.get_exposures()`
3. Call `add_calib` to add calibration exposures (FLAVOR = arc, flat) and assign exposure IDs
4. Write out that exposures table to a file

Nominally that output file would be `exposures.fits` and we wouldn't write the current `exposures.fits` that doesn't have arcs/flats or an EXPID column.

Update `desisim/bin/wrap-newexp` to use that `exposures.fits` file.  For backwards compatibility, if it is given an and old `exposures.fits` file that doesn't have an EXPID column, call `surveysim.add_calib`, but the default usage would be to expect that the `exposures.fits` file would contain EXPID and whatever arcs/flats are needed.

i.e. don't write the current `exposures.fits` that is missing EXPID, arcs/flats, and FLAVOR, but rather directly generate and write the one we want.

## FLAVOR vs. PROGRAM

We still need to sync up with ICS for naming details, but this is what we are currently using downstream:

FLAVOR = arc, flat, science, zero, dark
PROGRAM is only meaningful if FLAVOR=science, with PROGRAM options dark, bright, gray (and likely others added later).

This has the confusing aspect that FLAVOR=dark is very different from PROGRAM=dark.  The former is a closed shutter calibration exposure, the latter is a FLAVOR=science open shutter exposure of the main DESI survey during dark conditions (e.g. when the moon is down).

"zero" is what BOSS would call a "bias" exposure, i.e. closed shutter 0-length exposure.  I think the "zero" name comes from DES.

## Default values

Let's fill in columns that would be meaningful for a calibration exposure:
* NIGHT
* EXPTIME
* MJD (I don't like MJD creeping in, vs. UTC datestamps or TAI, but OK for now...)

with default meaningless values like -999 for things that don't apply to calibration exposures:
* TILEID, PASS, RA, DEC, SEEING, TRANSPARENCY, AIRMASS, MOONFRAC, MOONALT, MOONSEP

**Comment by weaverba137** [comment]
@sbailey, this is very helpful.  The only remaining question I have is: what *are* the meaningful values of EXPTIME for flats, arcs and darks, assuming that zero exposures really do have EXPTIME = 0?

**Comment by weaverba137** [comment]
Ach, two more questions:

1. The values of 'PROGRAM' are capitalized, but the values of 'FLAVOR' are not?
2. Would 'NONE' be an acceptable dummy value for 'PROGRAM', or would you prefer an empty string?

**Comment by sbailey** [comment]
EXPTIME=10 seconds each wouldn't be crazy.  For no particularly good reason, currently the code will scale the photons for a flat exposure based upon exposure time (default 10 sec), and it will ignore any exposure time for arcs.

And yes, PROGRAM values are capitalized (traces back to them being capitalized in the desi-tiles.fits file) and FLAVOR values are not (random choice).

How about PROGRAM='CALIB' if FLAVOR in (arc, flat, zero, dark)?

**Comment by weaverba137** [comment]
@sbailey, thank you this sounds good.

**Comment by weaverba137** [comment]
I think I've got a rough draft ready, see PR #275, and make comments there.
