### ISSUE TITLE
QSO templates should optionally include DLAs

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#296]
`desisim.templates.QSO` (and `desisim.templates.SIMQSO` once #293 has been merged) should optionally include DLAs in the Lyman-alpha forest.  This issue is related to #294 and #220.

**Comment by andreufont** [comment]
Hi @moustakas , @julienguy, @profxj ,

We want to separate the function that creates quasar templates from the function that generates quasar templates. 

We should have:
- a function that generates the quasar continua (given z and magnitude)
- a function that (optionally) adds Lya transmission.
- a function that (optionally) adds DLAs. 
- a function that (optionally) adds metal absorption.
- ...

Of course, we could also have a function that wraps all the above, but we want the functions above to be distinct and modular. Sometimes we will generate DLAs on the fly (using the code from @profxj ), but often we'll want to read the positions of the DLAs from a separate simulation file (similar to how we read the Lya skewers).

The only thing that might fit well within quasar template generation are BALs, since in a way this could be understood as part of the actual continua (it happens before the light escapes the halo).

**Comment by andreufont** [comment]
@moustakas - this is already implemented, isn't it?

If not, @alxogm is probably the best person to look into it.

**Comment by moustakas** [comment]
This is done now as an option to `quickquasars`; closing.
