### ISSUE TITLE
desisim.templates.SIMQSO.make_templates() has no option `restframe`

### ISSUE THREAD

**Issue by londumas** [desihub/desisim#324]
`desisim.templates.SIMQSO.make_templates()` has no option `restframe`.
This option is useful to build PCA because without it leads to empty data.

**Comment by londumas** [comment]
same for desisim.templates.QSO.make_templates()``

**Comment by moustakas** [comment]
The only reason this is a non-trivial change is that `wave` would have to be a `flux`-shaped vector, one for each template.  (This situation is slightly different than for the other target classes because the QSO templates are all rendered in the observed frame by construction.)

Would this be OK @londumas?

**Comment by londumas** [comment]
@moustakas, There is no rush to correct this. I can use the current to build PCAs.
I have no strong opinions on weather it is ok to have wave be a flux shaped vector or not.

**Comment by londumas** [comment]
@moustakas, the main reason to get the option `restframe` is to get the full spectrum in order to use it to build PCAs and achetypes. Would that be possible?

**Comment by moustakas** [comment]
Addressed in #377.
