### ISSUE TITLE
double vs floating point precision in simulated spectra

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#33]
The simulated spectra written out by newexp-desi and quickgen are double, rather than floating-point precision. Is this intentional?

**Comment by sbailey** [comment]
No.  32-bit floats should be sufficient, and would save disk space.

I opened a new issue on desispec for this (#85
<https://github.com/desihub/desispec/issues/85>) which covers the quickgen
case (since that uses desispec.io.write_frame).  I'll upgrade this
"question" issue to a "enhancement" to track it on the desispec side.

Stephen

**Comment by sbailey** [comment]
On the simspec side, newexp-desi now writes float images for flux and photons, though the wavelength array is still double.  That's overkill for the wavelength array, but avoids irritating x.9999999 style rounding and the 1D wavelength arrays are minor compared to the 2D flux and photon arrays anyway.

quickgen still outputs doubles, but that is because it is using the desispec.io routines as it should.  Fixing it on the desispec side will fix it on the desisim side, so I'll close this desisim ticket now.
