### ISSUE TITLE
SIMQSO vs QSO  class in quickquasar to add BAL

### ISSUE THREAD

**Issue by alxogm** [desihub/desisim#369]
@moustakas @julienguy @forero  The BAL feature addition is in  QSO class, but quickquasar uses SIMQSO...  I tried to used it and  quickquasar runs, but there are some arguments given to SIMQSO that can't be given to QSO class... 

https://github.com/desihub/desisim/blob/bc13ac374def771de8903fc2fdcabbab05125309/py/desisim/scripts/quickquasars.py#L486

**Comment by julienguy** [comment]
bal functions have to be in a separate and unique file, and then called in the various qso template generators.t

**Comment by alxogm** [comment]
@julienguy then I'll remove these lines, in order to make the PR, and then @forero and @Luz can work on the BAL addtion. Because the rest of the modifications, are indepenpenden of this. Is that ok?

**Comment by moustakas** [comment]
@julienguy I would appreciate it if you would take a moment and read the code I have written rather than criticizing it while at the same time saying that you don't understand it.

For many reasons, including speed and "one-stop-shopping" for many users other than the Lyman-alpha working group, it is *not* the case that the "[BAL] functions have to be in a separate and unique file, and then called in the various [QSO] template generators".  It is very convenient to be able to include these additional features (ditto for the "quick" Lyman-alpha forest functionality) without having to do more than call a single function.

However, for more custom work, including that of the Lyman-alpha working group, the BAL, DLA, and Lyman-alpha forest functionality does indeed have to be modular -- we are in complete agreement.

So: now that #321 has been merged (which was slow broke `desisim.templates` functionality) I am now adding that modularity (in the *morebals* branch).  When I open the PR I'll include (simple) instructions of how the module can be used (e.g., in `quickquasars` or wherever).

**Comment by moustakas** [comment]
@alxogm If you get a chance please take a look at #370 and see if that functionality is simple and easy enough to use in `quickquasars`.  If not, please submit your PR and assign me to take a look at what functionality you would like the BAL code to have.

**Comment by andreufont** [comment]
@alxogm @LuzGarciaP @forero - Is this issue now fixed? Can we add BALs both in quickquasars and in quickspectra, both using QSO and using SIMQSO?

**Comment by julienguy** [comment]
quickquasars uses desisim.templaltes.SIMQSO only for now but it would be trivial to add an option to use desisim.templates.QSO

**Comment by forero** [comment]
@andreufont not yet. We got caught up in the reproducibility issue. We can add the option to use desisim.templates.QSO.

**Comment by forero** [comment]
@andreufont I've opened this PR : #401
