### ISSUE TITLE
minimum rest-frame SIMQSO wavelength

### ISSUE THREAD

**Issue by londumas** [desihub/desisim#381]
When using `SIMQSO(restframe=True).make_templates()`, the rest-frame wavelength range is fixed to `[900, 60003]`. The issue is that a quasar at a redshift `z=4` already has pixels bellow `900`:
`3600./(1.+4.) =720.0`. Would it be hard to change `900.` to `450.` so that even a quasar at `z=7` could be used?
@moustakas, sorry I should have looked at that on my review.

**Comment by londumas** [comment]
On a side note, is it normal that when using `SIMQSO(restframe=True)` we get no Lyman-alpha forest?

**Comment by londumas** [comment]
Another issue with the current implementation of `SIMQSO(restframe=True).make_templates()` is that it produces quasars at `z=1.e-3`. However a quasar at `z=0` should be very different from a quasar at `z=3`.

**Comment by moustakas** [comment]
Apologies for the bad form, but I went ahead and changed the minimum rest-frame wavelength in `templates.SIMQSO` to 450 A in the master branch.

**Comment by moustakas** [comment]
Regarding your second comment, the `z=1e-3` "pivot redshift" I introduced in the code was just an arbitrary non-zero value I had to use since the quasar spectra themselves are generated by [simqso](https://github.com/imcgreer/simqso), and `z=0` causes problems (in the luminosity function sampling, the calculation of the luminosity distance, etc.).

Other than in the Lyman-alpha forest, how is a `z=3` quasar different from a `z=0` quasar?  There's the Baldwin effect, but since the normalization of the rest-frame spectra is arbitrary then we only need to think about how to incorporate differences in line-width, right?

Finally, I don't understand how the redshift-dependent Lyman-alpha forest should be handled when `restframe=True`.  For example we could use `z=3` as the pivot redshift... I welcome any suggestions (or please submit a PR -- I am by no means an expert on this subject).

One last thought:  I wonder if it would make more sense to build archetypes by calling simqso itself. There are a bunch of notebooks here that may be useful
  https://github.com/imcgreer/simqso/blob/master/examples
like, e.g., 
  https://github.com/imcgreer/simqso/blob/master/examples/GridExamples.ipynb
and 
  https://github.com/imcgreer/simqso/blob/master/examples/bossqsos_example.ipynb

**Comment by londumas** [comment]
fixed in https://github.com/desihub/desisim/pull/383
