### ISSUE TITLE
QSO.make_templates should be able to draw magnitudes from Luminosity Function

### ISSUE THREAD

**Issue by andreufont** [desihub/desisim#404]
When generating correlated Lyman alpha mock spectra, we read quasar redshifts and angular positions from the "transmission files", but we do not read magnitudes. 

When using SIMQSO.make_templates we can pass a magnitude range and a quasar redshift, and we will get a random magnitude following a given QSO LF. It would be great to have the same feature in QSO.make_template (either from the same QSO LF or from another one).

Ideally, we would like to have two different behaviors: 
 - when generating mocks that will go through target selection, we would use a realistic luminosity function.
 - when generating mocks that will not go through target selection, we would use the expected distribution of magnitudes observed by DESI.

This double functionality should also be implemented in SIMQSO.

**Comment by moustakas** [comment]
Sounds good, any contributions would be more than welcome.

Note that this issue is related to #106.

**Comment by andreufont** [comment]
True, I didn't realize that there was a similar ticket open. Hopefully we can close both soon :-)

**Comment by moustakas** [comment]
Some additional notes:

In `templates.SIMQSO` we sample from a specified luminosity function here-- 
https://github.com/imcgreer/simqso/blob/master/simqso/sqgrids.py#L1223-L1264

The default luminosity function in `SIMQSO` is from [BOSS/DR9](https://arxiv.org/abs/1210.6389), as written down here (although there are other choices)--
https://github.com/imcgreer/simqso/blob/master/simqso/sqmodels.py#L222-L235

Finally, @dkirkby developed some code for sampling from the [Palanque et al. 2012](https://arxiv.org/abs/1209.3968), [Palanque et al. 2015](https://arxiv.org/abs/1509.05607) luminosity functions--
  https://github.com/dkirkby/ArgonneLymanAlpha/blob/master/notebooks/SampleProperties.ipynb

I can't take the lead on this but hopefully someone from the Lya WG can implement the requisite changes.

**Comment by andreufont** [comment]
@alxogm - could you think of someone that might be able to implement these? If we wanted to use templates.QSO this would be important, although I guess we could decide to continue using SIMQSO.

**Comment by andreufont** [comment]
@moustakas @alxogm , fixing this should be a priority for the Lyman alpha working group.

Ideally, one would decouple the question of drawing random magnitudes from the question of generating quasar templates. So I would like to have two functions, outside of either SIMQSO or QSO:

1) for a particular quasar redshift, and for a particular filter (DECaLS-r, BASS_MZLS_g...), return a random magnitude following the expected distribution that we will observe with DESI. This is the one that we will use in quickquasars when not running target selection.

2) for a particular quasar redshfit, and some magnitude range (not sure whether it should be absolute magnitude MABS_1450 or one arbitrary filter like DECaLS-r, probably it doesn't matter), return a random absolute magnitude MABS_1450 that we can use to generate a random quasar template. We would call this function when running full survey simulations, or when running quickquasars *with* target selection. I guess this is what is currently being used, right @moustakas ?

**Comment by alxogm** [comment]
OK. I have asked @LuzGarciaP to keep an eye on this thread and see if she can help. Just to be sure, will we use the  Palanque et al. 2012, Palanque et al. 2015 luminosity functions?, similar to (and/or using ) what DKirkby made in his notebook (referenced above)?.

**Comment by andreufont** [comment]
@alxogm - for the "true QLF" yes, we should use any of the papers by Nathalie, I think this is already what is being used in SIMQSO? 

But what is really important is to add the option to use the "expected QLF in DESI", and for that we should ask the target selection working group for their best current estimate. Let me find the file.

**Comment by andreufont** [comment]
@alxogm - this is the file we should use to describe the "expected QLF in DESI": 
https://desi.lbl.gov/trac/browser/code/desimodel/trunk/data/targets/nzr_qso.dat

**Comment by alxogm** [comment]
> But what is really important is to add the option to use the "expected QLF in DESI", and for that we should ask the target selection working group for their best current estimate. Let me find the file.

@andreufont Ok, now I get it. Thanks. 

As for the default in SIMQSO I think is BOSS/DR9, according to John's post above...

**Comment by andreufont** [comment]
So let's do this: 
 - use the file I attached for the "expected QLF in DESI"
 - use the BOSS/DR9 already in SIMQSO for the "true QLF"

Ideally we would do that for both SIMQSO and QSO, but what is very urgent is to get this running at least for SIMQSO (we can add this to QSO later)

**Comment by alxogm** [comment]
@andreufont @moustakas  Finally, I sat down to complete this, since we need it for addressing a TS question ...

![Screen Shot 2019-08-07 at 8 52 22 PM](https://user-images.githubusercontent.com/14896082/62669454-502d1000-b955-11e9-98bf-2c3cbf777fc0.png)
In this plot I compare what we get in quickquasars as is now, and what I get from adapting the code by Kirkby, referenced above. This is only for one pixel  that is why the default don¡t look so good...

What I did was to sample the magnitudes from the QLF given the redshift, and pass this to SIMQSO instead of sampling from the default QLF, then proceed as usual...  I'll make more  tests before posting the branch for revision....

**Comment by andreufont** [comment]
Hi @alxogm - could you explain a bit better what you are plotting? What is the meaning of the different lines? Which ones are predictions and which ones are stochastic realizations? May be running on more pixels would make it a bit easier to see the differences between the different lines.

**Comment by alxogm** [comment]
![Screen Shot 2019-08-09 at 6 33 25 PM](https://user-images.githubusercontent.com/14896082/62814097-3534da00-bad4-11e9-8de4-29219a0f95dd.png)

Hi @andreufont, here is a comparison with a full run with downsampling=0.1 (London v9.0). The redline is what we called ([here](https://github.com/desihub/desisim/issues/404#issuecomment-423381794)) the "expected QLF in DESI", while the blue line is the magnitudes as being sampled from SIMQSO  here https://github.com/imcgreer/simqso/blob/master/simqso/sqmodels.py#L222-L235
 and the orange are the result of sampling the magnitudes from the redline. Everything is normalized to the total number of qso's.  I think is working fine... 

In this plot I decided only to compare the SIMQSO default with the "expected QLF".  I'll leave comparisons with the --target_selection option in quickquasars apart (since we have not used it much), as well as the modifications to the expected QLF in DESI...

So, I think this is working for SIMQSO, I'll see if I can add the same to QSO, before posting a PR.

**Comment by alxogm** [comment]
Hi @andreufont.  Implementation worked for QSO as well. Again in the plots I show the magnitudes as being sampled from the default setup in SIMQSO(orange) and QSO (red), and the ones sampled from the QLF (green and purple). The ylabel, I changed it from QLF --> N/Ntot, since that is what I'm actually plotting from the quickquasar runs, the blue line corresponds then to the QLF marginalized over redshift, and normalized to 1.  As described in  https://github.com/dkirkby/ArgonneLymanAlpha/blob/master/notebooks/SampleProperties.ipynb

The code I added to quickquasars is here: https://github.com/desihub/desisim/tree/qquasar_Magdist a few lines were added to templates.py.

![Screen Shot 2019-08-19 at 11 12 57 AM](https://user-images.githubusercontent.com/14896082/63281491-72d2f900-c272-11e9-98b0-8f6c18c0e683.png)

Should I do a PR or we keep discussing it here?

 Thanks

**Comment by andreufont** [comment]
Could you describe this at the telecon next week? I'm still confused about the results... Is the drop at large values of MAG_R caused by the binning of the histogram? I would have expected that the true luminosity function would keep increasing to larger and larger values of MAG_R... Are you applying any target selection? May be making narrow binning in the histogram would help.

**Comment by alxogm** [comment]
Hi @andreufont , yes the drop is due to the binning, below is a plot for a 0.1 binsize. For the  SIMQSO and QSO the only cuts are due to the  magnitude range (17,22.7).
On the other hand, I'm using the  binning of 0.5 since the "expected" QLF https://desi.lbl.gov/trac/browser/code/desimodel/trunk/data/targets/nzr_qso.dat has such binning. In this case the drop is also in the sampling, because magnitudes are sampled with flat distribution within the bin ....   If we want a different binning for sampling from the QLF  we can try to resample it to a smaller binsize. 

(I'll check why the green line has two drops for MAG_R >22.5, instead of one as the purple one). 

Yes, we can discuss it a the telecon. 

![Screen Shot 2019-08-20 at 11 33 27 AM](https://user-images.githubusercontent.com/14896082/63365980-5dc39c00-c33e-11e9-9bbc-e28d28c6ac39.png)

**Comment by moustakas** [comment]
@alxogm @andreufont can we close this ticket?

**Comment by alxogm** [comment]
I think we can close the issue. For the new mocks we will draw the magnitudes based on the observed distributions.
