### ISSUE TITLE
restore adding SN spectra to desisim templates to a functioning state

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#414]
In #409 I broke how we add SNe to the various galaxy Classes in `desisim.templates`; fix it.

@sybenzvi please let me know if this issue becomes a blocking factor for any work you and your group are doing.

**Comment by sybenzvi** [comment]
@moustakas, we are not up to date with the master so this hasn't affected us yet.

**Comment by sybenzvi** [comment]
@moustakas, Ouail Kitouni and I created a sne_test branch of desisim and have SN Ia injection working again. The only difference between the branch and the previous working version is that we're not normalizing the flux using the r-filter. We'll tweak things this week and submit a pull request when it's ready for merger.

**Comment by moustakas** [comment]
What's the plan for getting your branch into `master`?

**Comment by sybenzvi** [comment]
Thanks for checking in @moustakas. I changed the interface pretty significantly during the past week and finally got it set up so that we can inject arbitrary transients, not just the single Ia model in DES_BASIS_TEMPLATES.

Regarding the plan, I'm 95% done. I need to clean up the metadata a little and make sncosmo a weak dependency of the new transients submodule. I should be ready to submit a PR this afternoon.
