### ISSUE TITLE
RA_TARGET changed to TARGET_RA

### ISSUE THREAD

**Issue by TEtourneau** [desihub/desisim#448]
Hello,

it seems that the column names in the extension FIBERMAP have changed.
It prevents desi_zcatalog to produce the zcat.

Here is the error I got when running desi_zcatalog:

Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desispec/master/bin/desi_zcatalog", line 91, in <module>
    ndtype=np.dtype( zbest.dtype.descr + [("RA",str(fibermap["RA_TARGET"].dtype)),("DEC",str(fibermap["DEC_TARGET"].dtype)),("MAG",str(fibermap["MAG"].dtype),fibermap["MAG"].shape[-1])])
ValueError: no field of name RA_TARGET

Does someone have encountered this bug ?

Thanks,
Thomas

Thomas

**Comment by andreufont** [comment]
Hi @TEtourneau - Yes, I believe desispec and desisim are not synchronized. 

You could try to fix it and submit a PR, but it is probably faster if @julienguy or @moustakas take a look at it?

**Comment by sbailey** [comment]
My bad!  As part of the fibermap refactor I had grepped for `RA_TARGET` in the py/desispec files, but not in bin, and our integration test doesn't use the `--fibermap` option which trips this bug.  I think I fixed this in the target_ra branch of desispec, though I haven't tested it at all.  Can you give it a quick try or at least post exactly what desi_zcatalog command you are running?

**Comment by julienguy** [comment]
I would be useful if desi_zcatalog is backward compatible for a while given all the datachallenge data from previous version we have on disk.

**Comment by sbailey** [comment]
Backwards compatibility is a little messy because of `MAG` (old) vs. `FLUX_*` (new) so the final output catalog format is also different.  The code could do both with some if/then logic, but since we only have to run `desi_zcatalog` once per production, would it be ok to just say that old productions require an older version of desispec, and new productions require a newer version?

**Comment by julienguy** [comment]
Ideally one could write FLUX_* in the output catalog from the old MAG in the catalog if MAG is present in the fibermap. There is also the issue of the new truth table(s) format.

**Comment by sbailey** [comment]
OK, I added backwards compatibility, while writing a consistent output format in either case (RA, DEC, FLUX_G/R/Z) whether the inputs have RA/DEC_TARGET+MAG[] or TARGET_RA/DEC+FLUX_G/R/Z.

Note: the fix in in desispec branch target_ra, not desisim.  I didn't notice until now that this ticket was in desisim instead of desispec, but I don't want to lose the conversation.  I'll open a PR in a moment.

@julienguy please open a separate desispec ticket with what you suggest for how it should merge truth files, now that truth tables for different spectral classes are in different HDUs with different columns and different targets.
