### ISSUE TITLE
Updated BAL templates

### ISSUE THREAD

**Issue by paulmartini** [desihub/desisim#504]
Hi @moustakas, 

Just letting you know I've put a new BAL templates file in .../desi/spectro/templates/basis_templates/v3.1/ called bal_templates_v3.0.fits. 

The new templates file has about 1500 BAL templates (vs 500 for the previous version). Other improvements are extended wavelength coverage into the forest region (adding BAL features associated with OVI, LyA, and NV), as well as various measured properties of the BALs (BI, AI, etc.) from which the templates were derived.

**Comment by sbailey** [comment]
Thanks for these new templates.

@paulmartini please add these to the SVN repo in data/basis_templates/trunk  (browsable at https://desi.lbl.gov/trac/browser/data/basis_templates/trunk), i.e. we should add to SVN and make new tags from there rather than adding files directly to the checkouts/exports of tags of the SVN repo.  At NERSC there is /global/project/projectdirs/desi/spectro/templates/basis_templates/trunk which can be updated and used if someone wants the latest and greatest templates even if they don't appear in a tag yet.

**Comment by moustakas** [comment]
Done in #513.
