### ISSUE TITLE
'FIBERASSIGN' changed to 'FASSIGN' in fiberassign output files

### ISSUE THREAD

**Issue by alxogm** [desihub/desisim#528]
I tried to generate a catalog after running the fiberassign instruction in the tutorial https://github.com/desihub/tutorials/blob/master/FiberAssignMocks.ipynb in a previously generated catalog. 

but quickcat complains because in the fiberassign files it is called 'FASSIGN' instead of 'FIBERASSIGN' See  https://github.com/desihub/desisim/blob/7b9207638d289ad316642d77f9eeeb75a7fb8227/py/desisim/quickcat.py#L591
@forero Should I just push a small PR to fix it or is it being fixed somewhere else ?

**Comment by tskisner** [comment]
The FASSIGN HDU is in the raw data format.  After merging target data, the HDU is named "FIBERASSIGN".  Since that notebook uses the "fiberassign" wrapper script, it should be doing the merging under the hood.  I'm surprised that the output does not contain this HDU.

Can you please file an issue in the tutorials git repo?  In any case, the "FIBERASSIGN" HDU is the one you should be using in all cases unless you are intentionally only using the raw data files without the full set of target properties merged in.

**Comment by alxogm** [comment]
Oh, I see... I actually did not ran the full tutorial, only used the fiberassigment lines, maybe is my issue then! Let me check.
