### ISSUE TITLE
desisim.templates failing with new version of desitarget

### ISSUE THREAD

**Issue by julienguy** [desihub/desisim#553]
in desisim.templates is called : `self.colorcuts_function(gflux=gflux, rflux=rflux, zflux=zflux,
                                                        w1flux=w1flux, w2flux=w2flux, south=south)`
where `self.colorcuts_function` is for the class BGS the function `desitarget.cuts.isBGS_colors`
which arguments changes with desitarget PR https://github.com/desihub/desitarget/pull/718
(there is no more w2flux ...)

**Comment by sbailey** [comment]
Indeed, @geordie666 suggested letting the main survey targeting settle out, and then fix up the mocks to match instead of chasing a moving target in the past few weeks.  Has that time arrived?  @moustakas ?

@julienguy is this urgent for updating TSNR (or other urgent work) or would an older release be sufficient for right now?

**Comment by moustakas** [comment]
Fixed in #556.
