### ISSUE TITLE
path/environment variables issues with pixel simulations on laptop

### ISSUE THREAD

**Issue by julienguy** [desihub/desisim#66]
It's difficult to run pixel level simulations on a laptop, because there are too many environment variables to set, some hard-coded path, and some inconsistencies in path , and  too many python packages to have this running. 

* packages (and I might be missing some )
```
desiutil,desispec,specter,specsim,desisim,desimodel(git),desimodel(svn)
```

*  One needs 5 environment variables to get 1 sim running , we should deflate this 
```
export PIXPROD=0
export PRODNAME=0
export DESI_SPECTRO_SIM=/home/guy/Projets/DESI/analysis/pixelsims
export DESI_ROOT=/home/guy/Projets/DESI/analysis/pixelsims
export DESI_SPECTRO_DATA=/home/guy/Projets/DESI/analysis/pixelsims
```
There is a semi hard-coded path in desisim/obs.py
```
infile = os.getenv('DESI_ROOT')+'/spectro/templates/calib/v0.2/arc-lines-average.fits
```

After successfully running 
```
newexp-desi --flavor=arc --expid=0 --nspec=25
newexp-desi --flavor=flat --expid=1 --nspec=25
```
I got another path problem when running
```
pixsim-desi --night=20160126 --expid=0 --cameras=b0 --nspec=25 --ncpu=12
pixsim-desi --night=20160126 --expid=1 --cameras=b0 --nspec=25 --ncpu=12
```
in desispec/io/fibermap.py 
```
IOError: cannot open/home/guy/Projets/DESI/analysis/pixelsims/20160126/fibermap-00000000.fits
```
The only fix I found is with a symbolic link 
```
ln -fs 0/20160126 20160126
```

**Comment by weaverba137** [comment]
Leaving aside the number of environment variables for now, you *definitely* don't want to set `PIXPROD` or `PRODNAME` to values that might evaluate as `False`.  Those should be strings.

**Comment by sbailey** [comment]
Even though I'm the original author of pixsim-desi, I agree this is a pain.

I suggest we keep the BOSS-like system of environment variables to set default path locations, while augmenting that with command line options to override output locations if you want to run a simulation outside of the data model directory structure ecosystem.

The need for a symbolic link smells like an outright bug, but it is surprising to me that it hasn't popped up before.  I agree with Ben's point about avoiding environment variable names that might eval as False rather than a string, but I'm not sure that is the underlying problem here.

**Comment by weaverba137** [comment]
Was there ever a resolution to this?  The bug itself is serious, but I'm concerned that the general philosophical point about setting environment variables may be yet another unresolved discussion we need to conclude.

**Comment by sbailey** [comment]
Both Ted and I have successfully run pixsim since then without problem, so that bug is some corner case found by Julien's environment, not a blocking factor for all pixsim usage.  If Julien has updates on what did or did not work, that would be useful to know.

I'd like to make pixsim easier to use, but I'm less concerned about this env var vs. command line options philosophical point than the other ongoing discussions about dependencies.  It's a style issue — I tended to code BOSS-style with heavy dependency upon canonical environment variables and a rigid directory structure; Julien tended to code more flexibly while requiring 5 lines worth of command line options to do even simple things.  I currently think a hybrid is best — always allow full command line options like Julien, while resorting to env var based defaults if they aren't specified.

**Comment by weaverba137** [comment]
The documentation here addresses this problem: https://desi.lbl.gov/trac/wiki/Pipeline/Install#SetNecessaryEnvironmentVariablesandData
If this is insufficient, please open a new issue with specific concerns.
